#!/usr/bin/env bash
#
# Launch the application and any extra required processes locally.

set -e

cd "$(dirname "$0")/.."

test -z "$RACK_ENV" &&
  RACK_ENV='development'

# boot the app and any other necessary processes
bundle exec jekyll serve --watch "$@"
